server:
  port: 9001

spring:
  application:
    name: AWM-consumer-Machine-9001
# Eureka配置
eureka:
  client:
    register-with-eureka: true # 向Eureka注册自己
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    instance-id: AWMconsumer-9001 # 修改eureka上的默认描述信息
    prefer-ip-address: true
