server:
  port: 8092

# mybatis配置
mybatis:
  type-aliases-package: com.ttmy.awm.api.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

# spring配置
spring:
  application:
    name: AWM-provider-UserServer-8092
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/awmusers?userSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: system

# Eureka的配置,服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    instance-id: UserServer-8092 # 修改eureka上的默认描述信息
    prefer-ip-address: true

# info配置
info:
  app.name: AutoWashingMachine
  company.name: DSDcompany-TTMY