server:
  port: 9158
# spring配置
spring:
  security:
    user:
      name: user
      password: system
  application:
    name: AWM-provider-author-9158
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/awmusers?userSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: system
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1800000
# Eureka的配置,服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    instance-id: AuthorServer-9158 # 修改eureka上的默认描述信息
    prefer-ip-address: true