server:
  port: 7001

#Eureka
eureka:
  instance:
    hostname: 127.0.0.1 # Eureka服务端的实例名称
  client:
    register-with-eureka: false # 表示是否向eureka注册中心注册自己
    fetch-registry: false # fetch-registry如果为false,则表示自己为注册中心
    service-url: # 监控页面
      # 集群模式：http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/