server:
  port: 9527
spring:
  application:
    name: AWM-zuul-9527
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/awmusers?userSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: system
  redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 1800000
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    instance-id: zuul9527 # 修改eureka上的默认描述信息
    prefer-ip-address: true
# 路由网关配置
zuul:
  host:
    connect-timeout-millis: 3000 #ms HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 3000  #ms socket通信超时
  #饥饿加载
  ribbon:
    eager-load:
      enabled: true
  prefix: /AWM # 公共设置的前缀
  ignored-services: "*"# 不能再使用这个路径访问了，ignore : 忽略 | “*” 隐藏全部的微服务真实路径
  routes:
    AWMUserServer:
      path: /PROVIDERUSER/**
      serviceId: AWM-PROVIDER-USERSERVER-8092
    AWMMachineServer:
      path: /PROVIDERMACHINE/**
      serviceId: AWM-PROVIDER-MACHINESERVER-8091
    AWMOrderServer:
      path: /PROVIDERORDER/**
      serviceId: AWM-PROVIDER-ORDERSERVER-8093
ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
hystrix:
  command:
    default:
    execution:
    isolation:
    thread:
    timeoutInMilliseconds: 3000 # 设置hystrix的超时时间为1000ms