server:
  port: 9002

spring:
  application:
    name: AWM-consumer-User-feign-9002

# 开启降级 feign.histrix
feign:
  hystrix:
    enabled: true
# Eureka配置
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    instance-id: AWMconsumer-9002 # 修改eureka上的默认描述信息
    prefer-ip-address: true